### PR TITLE
Add bottom-k MinHash

### PR DESCRIPTION
**Pull request by jianshu93**
Hello Jean,

Since you are updating probminhash crate recently, I suggest we move the bottom-k minhash in kmerutils to here as a comparison (I mentioned a while ago but forget about it later on). I just copied your code from kmerutils here and added readme. Feel free to commit yourself but I just want to keep a record here what changes should be made. All tests passed. 

Thanks,

Jianshu

### CODE REVIEW

**Comment by jean-pierreBoth** [comment]
done

**Comment by jean-pierreBoth** [comment]
In fact minhash should have been added in lib.rs.... Then it requires also kmerutils::hashed which is a bit out of context in probminhash, so it is better to leave minhash in kermutils.

**Comment by jean-pierreBoth** [comment]
Hello Jianshu,

In fact kmerutils was my first step in Rust and is not so well desingned,
minhash relies on kmerutils::hashed which was weighted with useless
complexity.
So it is best to keep it as such.


Le mer. 18 sept. 2024 à 18:40, Jianshu_Zhao ***@***.***> a
écrit :

**Comment by jianshu93** [comment]
ok sounds good to me. I did not realize we need the hashed to add to lib.rs

Jianshu

**Pull request merged**
